import Config

# Configure your database (Docker PostgreSQL 18 on port 5433)
config :secure_sharing, SecureSharing.Repo,
  username: "securesharing",
  password: "securesharing_dev",
  hostname: "localhost",
  port: 5433,
  database: "securesharing_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 30,
  queue_target: 5000,
  queue_interval: 5000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :secure_sharing, SecureSharingWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1VM1/RrX5taCz+mqo4mq4q38lxI2R/Vgm2EyTPzNhkbJjKe/82gJarkAwjuCOGQV",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :secure_sharing, dev_routes: true

# Disable rate limiting for development and E2E testing
config :secure_sharing, :rate_limit_enabled, false

# WebAuthn configuration for development
config :secure_sharing, :webauthn_origin, "http://localhost:4000"

# Storage - S3 configuration using Garage (S3-compatible)
# Start Garage with: podman run -d --name garage -p 3900:3900 ...
config :secure_sharing, SecureSharing.Storage,
  provider: SecureSharing.Storage.Providers.S3,
  bucket: "securesharing-files",
  region: "garage"

config :ex_aws,
  access_key_id: "GK59d7e0e6b6a19033bd362ca3",
  secret_access_key: "b85866b23b261d22711c3daba1d6ad9416d0ea57f88eaed85206d56e0997e949",
  region: "garage"

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 3900

# OneSignal - Push notifications for development
config :secure_sharing, SecureSharing.Notifications.OneSignal,
  app_id: "265f3b98-a29f-405c-b45e-d104b1c9aec0",
  api_key:
    "os_v2_app_ezptxgfct5afznc62ecldsnoybf6sxv664yur75ulodkk7u5nj7i32lvyk4gjub5idm3f6jtjgxxzikeeb34c6vfpqdapa6lg2q5spi"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
