defmodule SecureSharing.Crypto.Providers.MLKEM do
  @moduledoc """
  ML-KEM (NIST FIPS 203) provider implementation.

  Wraps the MlKem NIF module to conform to the KEMProvider behaviour.

  ML-KEM-768 provides approximately 192-bit classical security and
  128-bit post-quantum security (NIST security level 3).

  ## True KEM Semantics

  ML-KEM follows standard KEM semantics:
  - `encapsulate(pk)` generates a random shared secret and ciphertext
  - `decapsulate(ct, sk)` recovers the shared secret

  The shared secret is generated by the KEM, not provided by the caller.
  """

  @behaviour SecureSharing.Crypto.KEMProvider

  @impl true
  def init(_level \\ 192) do
    # We use ML-KEM-768 which provides ~192-bit classical security (NIST level 3)
    # The level parameter is accepted for API compatibility but we always use 192
    MlKem.init(192)
  end

  @impl true
  def initialized?, do: MlKem.initialized?()

  @impl true
  def get_level do
    if MlKem.initialized?() do
      # ML-KEM-768 is NIST level 3, roughly equivalent to 192-bit security
      {:ok, 192}
    else
      {:error, :not_initialized}
    end
  end

  @impl true
  def get_sizes do
    MlKem.get_sizes()
  end

  @impl true
  def keypair do
    case MlKem.keypair() do
      {:ok, public_key, private_key} ->
        {:ok, %{public_key: public_key, private_key: private_key}}

      other ->
        other
    end
  end

  @impl true
  def encapsulate(public_key) do
    case MlKem.encapsulate(public_key) do
      {:ok, ciphertext, shared_secret} ->
        {:ok, %{ciphertext: ciphertext, shared_secret: shared_secret}}

      other ->
        other
    end
  end

  @impl true
  def decapsulate(ciphertext, private_key) do
    # ML-KEM native decapsulation - recovers the shared secret
    MlKem.decapsulate(ciphertext, private_key)
  end

  @impl true
  def cleanup, do: MlKem.cleanup()

  @impl true
  def version, do: MlKem.version()

  @impl true
  def algorithm, do: "ML-KEM-768"
end
