defmodule SecureSharing.Crypto.KEMProvider do
  @moduledoc """
  Behaviour for Key Encapsulation Mechanism (KEM) providers.

  KEM is used to securely establish shared secrets between parties.
  This behaviour allows swapping between different KEM implementations
  (e.g., KAZ-KEM, ML-KEM) for algorithm agility.

  ## KEM Semantics

  A KEM provides two operations:

  1. **Encapsulate**: Given a public key, generate a random shared secret
     and a ciphertext that encapsulates it.
     `encapsulate(public_key) → {:ok, %{ciphertext, shared_secret}}`

  2. **Decapsulate**: Given a ciphertext and private key, recover the
     shared secret.
     `decapsulate(ciphertext, private_key) → {:ok, shared_secret}`

  The shared secret is generated by the KEM, not provided by the caller.
  This is the standard NIST FIPS 203 KEM interface.

  ## Security Levels

  All implementations must support these security levels:
  - 128 - 128-bit security
  - 192 - 192-bit security
  - 256 - 256-bit security

  ## Usage

      # Get the configured provider
      provider = SecureSharing.Crypto.kem_provider()

      # Initialize with security level
      :ok = provider.init(128)

      # Generate keypair
      {:ok, keypair} = provider.keypair()

      # Encapsulate - KEM generates the shared secret
      {:ok, %{ciphertext: ct, shared_secret: ss}} = provider.encapsulate(keypair.public_key)

      # Decapsulate to recover the shared secret
      {:ok, recovered_ss} = provider.decapsulate(ct, keypair.private_key)
      # recovered_ss == ss
  """

  @type level :: 128 | 192 | 256
  @type keypair :: %{public_key: binary(), private_key: binary()}
  @type encapsulation :: %{ciphertext: binary(), shared_secret: binary()}
  @type sizes :: %{
          public_key: non_neg_integer(),
          private_key: non_neg_integer(),
          ciphertext: non_neg_integer(),
          shared_secret: non_neg_integer()
        }

  @doc """
  Initialize the KEM provider with the specified security level.
  """
  @callback init(level()) :: :ok | {:error, atom()}

  @doc """
  Check if the provider has been initialized.
  """
  @callback initialized?() :: boolean()

  @doc """
  Get the current security level.
  """
  @callback get_level() :: {:ok, level()} | {:error, :not_initialized}

  @doc """
  Get the sizes of keys and ciphertext for the current security level.
  """
  @callback get_sizes() :: {:ok, sizes()} | {:error, :not_initialized}

  @doc """
  Generate a new KEM keypair.
  """
  @callback keypair() :: {:ok, keypair()} | {:error, atom()}

  @doc """
  Encapsulate: Generate a random shared secret and encapsulate it for the recipient.

  Returns both the ciphertext (to send to recipient) and the shared secret
  (to use locally for encryption). The shared secret is generated by the KEM.
  """
  @callback encapsulate(public_key :: binary()) ::
              {:ok, encapsulation()} | {:error, atom()}

  @doc """
  Decapsulate: Recover the shared secret from a ciphertext.

  Uses the private key to decapsulate and recover the shared secret that
  was generated during encapsulation.
  """
  @callback decapsulate(ciphertext :: binary(), private_key :: binary()) ::
              {:ok, shared_secret :: binary()} | {:error, atom()}

  @doc """
  Cleanup resources.
  """
  @callback cleanup() :: :ok

  @doc """
  Get the provider version.
  """
  @callback version() :: String.t()

  @doc """
  Get the algorithm name (e.g., "KAZ-KEM", "ML-KEM").
  """
  @callback algorithm() :: String.t()
end
