// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ssdid_sdk_ffiFFI)
import ssdid_sdk_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ssdid_sdk_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ssdid_sdk_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct FfiClaimEntry {
    public var name: String
    public var priority: FfiClaimPriority

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, priority: FfiClaimPriority) {
        self.name = name
        self.priority = priority
    }
}



extension FfiClaimEntry: Equatable, Hashable {
    public static func ==(lhs: FfiClaimEntry, rhs: FfiClaimEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.priority != rhs.priority {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(priority)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClaimEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClaimEntry {
        return
            try FfiClaimEntry(
                name: FfiConverterString.read(from: &buf), 
                priority: FfiConverterTypeFfiClaimPriority.read(from: &buf)
        )
    }

    public static func write(_ value: FfiClaimEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeFfiClaimPriority.write(value.priority, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClaimEntry_lift(_ buf: RustBuffer) throws -> FfiClaimEntry {
    return try FfiConverterTypeFfiClaimEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClaimEntry_lower(_ value: FfiClaimEntry) -> RustBuffer {
    return FfiConverterTypeFfiClaimEntry.lower(value)
}


public struct FfiKeyValue {
    public var key: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }
}



extension FfiKeyValue: Equatable, Hashable {
    public static func ==(lhs: FfiKeyValue, rhs: FfiKeyValue) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiKeyValue: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiKeyValue {
        return
            try FfiKeyValue(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiKeyValue, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyValue_lift(_ buf: RustBuffer) throws -> FfiKeyValue {
    return try FfiConverterTypeFfiKeyValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiKeyValue_lower(_ value: FfiKeyValue) -> RustBuffer {
    return FfiConverterTypeFfiKeyValue.lower(value)
}


public struct FfiRequestedClaim {
    public var name: String
    public var required: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, required: Bool) {
        self.name = name
        self.required = required
    }
}



extension FfiRequestedClaim: Equatable, Hashable {
    public static func ==(lhs: FfiRequestedClaim, rhs: FfiRequestedClaim) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.required != rhs.required {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(required)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRequestedClaim: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRequestedClaim {
        return
            try FfiRequestedClaim(
                name: FfiConverterString.read(from: &buf), 
                required: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRequestedClaim, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.required, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRequestedClaim_lift(_ buf: RustBuffer) throws -> FfiRequestedClaim {
    return try FfiConverterTypeFfiRequestedClaim.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRequestedClaim_lower(_ value: FfiRequestedClaim) -> RustBuffer {
    return FfiConverterTypeFfiRequestedClaim.lower(value)
}


public struct FfiVpResponse {
    public var vpToken: String
    public var presentationSubmission: String?
    public var nonce: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(vpToken: String, presentationSubmission: String?, nonce: String?) {
        self.vpToken = vpToken
        self.presentationSubmission = presentationSubmission
        self.nonce = nonce
    }
}



extension FfiVpResponse: Equatable, Hashable {
    public static func ==(lhs: FfiVpResponse, rhs: FfiVpResponse) -> Bool {
        if lhs.vpToken != rhs.vpToken {
            return false
        }
        if lhs.presentationSubmission != rhs.presentationSubmission {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(vpToken)
        hasher.combine(presentationSubmission)
        hasher.combine(nonce)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiVpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiVpResponse {
        return
            try FfiVpResponse(
                vpToken: FfiConverterString.read(from: &buf), 
                presentationSubmission: FfiConverterOptionString.read(from: &buf), 
                nonce: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiVpResponse, into buf: inout [UInt8]) {
        FfiConverterString.write(value.vpToken, into: &buf)
        FfiConverterOptionString.write(value.presentationSubmission, into: &buf)
        FfiConverterOptionString.write(value.nonce, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVpResponse_lift(_ buf: RustBuffer) throws -> FfiVpResponse {
    return try FfiConverterTypeFfiVpResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVpResponse_lower(_ value: FfiVpResponse) -> RustBuffer {
    return FfiConverterTypeFfiVpResponse.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCallback {
    
    case success(responseId: String
    )
    case denied
    case error(code: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCallback: FfiConverterRustBuffer {
    typealias SwiftType = FfiCallback

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCallback {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .success(responseId: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .denied
        
        case 3: return .error(code: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCallback, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .success(responseId):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(responseId, into: &buf)
            
        
        case .denied:
            writeInt(&buf, Int32(2))
        
        
        case let .error(code):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(code, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCallback_lift(_ buf: RustBuffer) throws -> FfiCallback {
    return try FfiConverterTypeFfiCallback.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCallback_lower(_ value: FfiCallback) -> RustBuffer {
    return FfiConverterTypeFfiCallback.lower(value)
}



extension FfiCallback: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiClaimPriority {
    
    case required
    case optional
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClaimPriority: FfiConverterRustBuffer {
    typealias SwiftType = FfiClaimPriority

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClaimPriority {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .required
        
        case 2: return .optional
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiClaimPriority, into buf: inout [UInt8]) {
        switch value {
        
        
        case .required:
            writeInt(&buf, Int32(1))
        
        
        case .optional:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClaimPriority_lift(_ buf: RustBuffer) throws -> FfiClaimPriority {
    return try FfiConverterTypeFfiClaimPriority.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClaimPriority_lower(_ value: FfiClaimPriority) -> RustBuffer {
    return FfiConverterTypeFfiClaimPriority.lower(value)
}



extension FfiClaimPriority: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCredentialFormat {
    
    case sdJwt
    case msoMdoc
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCredentialFormat: FfiConverterRustBuffer {
    typealias SwiftType = FfiCredentialFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCredentialFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sdJwt
        
        case 2: return .msoMdoc
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCredentialFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sdJwt:
            writeInt(&buf, Int32(1))
        
        
        case .msoMdoc:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialFormat_lift(_ buf: RustBuffer) throws -> FfiCredentialFormat {
    return try FfiConverterTypeFfiCredentialFormat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialFormat_lower(_ value: FfiCredentialFormat) -> RustBuffer {
    return FfiConverterTypeFfiCredentialFormat.lower(value)
}



extension FfiCredentialFormat: Equatable, Hashable {}




public enum FfiSdkError {

    
    
    case InvalidConfig(msg: String
    )
    case InvalidUrl(msg: String
    )
    case InvalidFormat(msg: String
    )
    case ResponseParseError(msg: String
    )
    case QrGenerationFailed(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSdkError: FfiConverterRustBuffer {
    typealias SwiftType = FfiSdkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSdkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidConfig(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidUrl(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidFormat(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .ResponseParseError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .QrGenerationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSdkError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidConfig(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidUrl(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidFormat(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .ResponseParseError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .QrGenerationFailed(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension FfiSdkError: Equatable, Hashable {}

extension FfiSdkError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiClaimEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiClaimEntry]

    public static func write(_ value: [FfiClaimEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiClaimEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiClaimEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiClaimEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiClaimEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiKeyValue: FfiConverterRustBuffer {
    typealias SwiftType = [FfiKeyValue]

    public static func write(_ value: [FfiKeyValue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiKeyValue.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiKeyValue] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiKeyValue]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiKeyValue.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRequestedClaim: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRequestedClaim]

    public static func write(_ value: [FfiRequestedClaim], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRequestedClaim.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRequestedClaim] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRequestedClaim]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRequestedClaim.read(from: &buf))
        }
        return seq
    }
}
public func buildAuthRequest(challenge: String, acceptedAlgorithms: [String], responseUrl: String, callbackScheme: String, extras: [FfiKeyValue])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_build_auth_request(
        FfiConverterString.lower(challenge),
        FfiConverterSequenceString.lower(acceptedAlgorithms),
        FfiConverterString.lower(responseUrl),
        FfiConverterString.lower(callbackScheme),
        FfiConverterSequenceTypeFfiKeyValue.lower(extras),$0
    )
})
}
public func buildCredentialOffer(issuerUrl: String, credentialType: String, format: FfiCredentialFormat, preAuthorizedCode: String, callbackScheme: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_build_credential_offer(
        FfiConverterString.lower(issuerUrl),
        FfiConverterString.lower(credentialType),
        FfiConverterTypeFfiCredentialFormat.lower(format),
        FfiConverterString.lower(preAuthorizedCode),
        FfiConverterString.lower(callbackScheme),$0
    )
})
}
public func buildCredentialRequest(credentialType: String, format: FfiCredentialFormat, claims: [FfiClaimEntry], responseUrl: String, callbackScheme: String, extras: [FfiKeyValue])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_build_credential_request(
        FfiConverterString.lower(credentialType),
        FfiConverterTypeFfiCredentialFormat.lower(format),
        FfiConverterSequenceTypeFfiClaimEntry.lower(claims),
        FfiConverterString.lower(responseUrl),
        FfiConverterString.lower(callbackScheme),
        FfiConverterSequenceTypeFfiKeyValue.lower(extras),$0
    )
})
}
public func buildLoginRequest(serverUrl: String, serviceName: String, challengeId: String, callbackScheme: String, requestedClaims: [FfiRequestedClaim], challenge: String?, serverDid: String?, serverKeyId: String?, serverSignature: String?, registryUrl: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_build_login_request(
        FfiConverterString.lower(serverUrl),
        FfiConverterString.lower(serviceName),
        FfiConverterString.lower(challengeId),
        FfiConverterString.lower(callbackScheme),
        FfiConverterSequenceTypeFfiRequestedClaim.lower(requestedClaims),
        FfiConverterOptionString.lower(challenge),
        FfiConverterOptionString.lower(serverDid),
        FfiConverterOptionString.lower(serverKeyId),
        FfiConverterOptionString.lower(serverSignature),
        FfiConverterOptionString.lower(registryUrl),$0
    )
})
}
public func generateQrCode(data: String, size: UInt32)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_generate_qr_code(
        FfiConverterString.lower(data),
        FfiConverterUInt32.lower(size),$0
    )
})
}
public func parseCallback(uri: String)throws  -> FfiCallback {
    return try  FfiConverterTypeFfiCallback.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_parse_callback(
        FfiConverterString.lower(uri),$0
    )
})
}
public func parseVpResponse(body: String)throws  -> FfiVpResponse {
    return try  FfiConverterTypeFfiVpResponse.lift(try rustCallWithError(FfiConverterTypeFfiSdkError.lift) {
    uniffi_ssdid_sdk_ffi_fn_func_parse_vp_response(
        FfiConverterString.lower(body),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ssdid_sdk_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_build_auth_request() != 36356) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_build_credential_offer() != 41782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_build_credential_request() != 38889) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_build_login_request() != 23489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_generate_qr_code() != 10092) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_parse_callback() != 36124) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssdid_sdk_ffi_checksum_func_parse_vp_response() != 62149) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all