/**
 * Test Helpers for E2E Testing
 *
 * Utilities for generating test data, mock crypto keys, etc.
 */

import * as crypto from 'crypto';

/**
 * Generate a random email address for testing
 */
export function generateTestEmail(prefix: string = 'testuser'): string {
  const timestamp = Date.now();
  const random = crypto.randomBytes(4).toString('hex');
  return `${prefix}-${timestamp}-${random}@e2e-test.local`;
}

/**
 * Generate a secure random password
 */
export function generateTestPassword(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%';
  let password = '';
  for (let i = 0; i < 16; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  // Ensure at least one of each required character type
  return password + 'Aa1!';
}

/**
 * Generate mock crypto keys for testing
 *
 * In a real scenario, these would be generated by the client-side crypto library.
 * For E2E testing, we use placeholder values that the server accepts.
 */
export function generateMockCryptoKeys() {
  // Generate random bytes and encode as base64
  const kemPublicKey = crypto.randomBytes(1184).toString('base64'); // ML-KEM-768 public key size
  const signPublicKey = crypto.randomBytes(1312).toString('base64'); // ML-DSA-65 public key size
  const encryptedMasterKey = crypto.randomBytes(48).toString('base64'); // AES-256-GCM encrypted key
  const masterKeyNonce = crypto.randomBytes(12).toString('base64'); // GCM nonce

  return {
    public_keys: {
      kem: kemPublicKey,
      sign: signPublicKey,
    },
    encrypted_master_key: encryptedMasterKey,
    master_key_nonce: masterKeyNonce,
  };
}

// KDF profile bytes (lower = stronger)
export const KDF_PROFILES = {
  ARGON2ID_STANDARD: 0x01,
  ARGON2ID_LOW: 0x02,
  BCRYPT_HKDF: 0x03,
} as const;

/**
 * Generate a tiered KDF salt: [profile_byte(1)] || [random(16)] = 17 bytes, base64-encoded
 */
export function generateTieredSalt(profileByte: number): string {
  const salt = Buffer.alloc(17);
  salt[0] = profileByte;
  crypto.randomBytes(16).copy(salt, 1);
  return salt.toString('base64');
}

/**
 * Generate mock crypto keys with a specific KDF profile salt
 */
export function generateMockCryptoKeysWithSalt(profileByte: number) {
  return {
    ...generateMockCryptoKeys(),
    key_derivation_salt: generateTieredSalt(profileByte),
  };
}

/**
 * Generate mock file metadata for upload testing
 */
export function generateMockFileMetadata(filename: string, content: string | Buffer) {
  const contentBuffer = Buffer.isBuffer(content) ? content : Buffer.from(content);
  const blobHash = crypto.createHash('sha256').update(contentBuffer).digest('hex');

  return {
    filename,
    content_type: 'text/plain',
    size: contentBuffer.length,
    encrypted_metadata: crypto.randomBytes(256).toString('base64'),
    metadata_nonce: crypto.randomBytes(12).toString('base64'),
    wrapped_dek: crypto.randomBytes(48).toString('base64'),
    kem_ciphertext: crypto.randomBytes(1088).toString('base64'), // ML-KEM-768 ciphertext size
    blob_hash: blobHash,
    signature: crypto.randomBytes(3309).toString('base64'), // ML-DSA-65 signature size
  };
}

/**
 * Sample documents with PII for testing redaction
 */
export const SAMPLE_DOCUMENTS = {
  simple: `
Hello, my name is John Smith and I live at 123 Main Street, New York, NY 10001.
You can reach me at john.smith@example.com or call me at (555) 123-4567.
My social security number is 123-45-6789 and my date of birth is January 15, 1985.
`.trim(),

  medical: `
PATIENT RECORD

Name: Jane Doe
DOB: 03/22/1990
SSN: 987-65-4321
Medical Record Number: MRN-2024-001234

Address: 456 Oak Avenue, Apt 7B, Los Angeles, CA 90001
Phone: (310) 555-0123
Email: jane.doe@healthcare.test

Emergency Contact: Robert Doe (Husband)
Phone: (310) 555-0124

DIAGNOSIS: Type 2 Diabetes
MEDICATIONS: Metformin 500mg twice daily

Dr. Sarah Johnson, MD
License #: CA-MD-12345
`.trim(),

  financial: `
BANK STATEMENT

Account Holder: Michael Chen
Account Number: 1234567890
Routing Number: 021000021
SSN: 456-78-9012

Transaction History:
- 01/15/2024: Direct Deposit from Acme Corp - $5,432.10
- 01/16/2024: Online Payment to Visa ending in 4532 - $1,234.56
- 01/17/2024: ATM Withdrawal at 789 Broadway, NYC - $200.00

Credit Card: 4532-1234-5678-9012
Expiration: 12/25
CVV: 123

For questions, contact customer service at banking@test.com
or call 1-800-555-BANK (2265).
`.trim(),

  minimal: 'Contact John at john@example.com for more info.',

  noPii: `
The quick brown fox jumps over the lazy dog.
This is a sample document with no personally identifiable information.
It contains only generic text for testing purposes.
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
`.trim(),
};

/**
 * Expected PII types that should be detected
 */
export const EXPECTED_PII_TYPES = {
  simple: ['PERSON', 'EMAIL', 'PHONE', 'SSN', 'ADDRESS', 'DATE'],
  medical: ['PERSON', 'EMAIL', 'PHONE', 'SSN', 'ADDRESS', 'DATE', 'MEDICAL_RECORD'],
  financial: ['PERSON', 'EMAIL', 'PHONE', 'SSN', 'CREDIT_CARD', 'BANK_ACCOUNT'],
  minimal: ['PERSON', 'EMAIL'],
  noPii: [],
};

/**
 * Wait utility with exponential backoff
 */
export async function waitWithBackoff(
  checkFn: () => Promise<boolean>,
  options: {
    maxAttempts?: number;
    initialDelayMs?: number;
    maxDelayMs?: number;
    backoffMultiplier?: number;
  } = {}
): Promise<void> {
  const {
    maxAttempts = 10,
    initialDelayMs = 1000,
    maxDelayMs = 30000,
    backoffMultiplier = 2,
  } = options;

  let delay = initialDelayMs;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const success = await checkFn();
    if (success) {
      return;
    }

    if (attempt < maxAttempts) {
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay = Math.min(delay * backoffMultiplier, maxDelayMs);
    }
  }

  throw new Error(`Condition not met after ${maxAttempts} attempts`);
}

/**
 * Retry a function with exponential backoff
 */
export async function retryWithBackoff<T>(
  fn: () => Promise<T>,
  options: {
    maxAttempts?: number;
    initialDelayMs?: number;
    maxDelayMs?: number;
    backoffMultiplier?: number;
    shouldRetry?: (error: Error) => boolean;
  } = {}
): Promise<T> {
  const {
    maxAttempts = 3,
    initialDelayMs = 1000,
    maxDelayMs = 10000,
    backoffMultiplier = 2,
    shouldRetry = () => true,
  } = options;

  let delay = initialDelayMs;
  let lastError: Error | undefined;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error as Error;

      if (attempt >= maxAttempts || !shouldRetry(lastError)) {
        throw lastError;
      }

      await new Promise((resolve) => setTimeout(resolve, delay));
      delay = Math.min(delay * backoffMultiplier, maxDelayMs);
    }
  }

  throw lastError!;
}

/**
 * Assert that text contains expected redaction markers
 */
export function assertRedacted(
  redactedText: string,
  originalText: string,
  expectedTypes: string[]
): void {
  // Check that original PII values are not present
  const piiPatterns = [
    /\b\d{3}-\d{2}-\d{4}\b/, // SSN
    /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/, // Email
    /\b\d{4}-\d{4}-\d{4}-\d{4}\b/, // Credit card
    /\(\d{3}\)\s*\d{3}-\d{4}/, // Phone
  ];

  for (const pattern of piiPatterns) {
    const originalMatches = originalText.match(pattern);
    if (originalMatches) {
      for (const match of originalMatches) {
        if (redactedText.includes(match)) {
          throw new Error(`PII value "${match}" was not redacted`);
        }
      }
    }
  }

  // Check for redaction markers
  const redactionMarkerPattern = /\[([A-Z_]+)\]/g;
  const foundMarkers = [...redactedText.matchAll(redactionMarkerPattern)].map((m) => m[1]);

  for (const expectedType of expectedTypes) {
    if (!foundMarkers.some((m) => m.includes(expectedType) || expectedType.includes(m))) {
      console.warn(
        `Expected redaction marker for ${expectedType} not found. Found: ${foundMarkers.join(', ')}`
      );
    }
  }
}
