defmodule SecureSharingWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :secure_sharing

  # The session will be stored in the cookie, signed and encrypted.
  # Both signing_salt and encryption_salt should be different random strings.
  # Generate with: mix phx.gen.secret 32
  @session_options [
    store: :cookie,
    key: "_secure_sharing_key",
    signing_salt: "pT9lo6wo",
    # Enables AES-GCM encryption of session data
    encryption_salt: "Kx7nL2mQ",
    same_site: "Lax",
    # Only send cookie over HTTPS
    secure: true,
    # Prevent JavaScript access
    http_only: true,
    # 7 days
    max_age: 86_400 * 7
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", SecureSharingWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :secure_sharing,
    gzip: not code_reloading?,
    only: SecureSharingWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :secure_sharing
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # CORS — allow API access from web and desktop clients
  plug Corsica,
    origins: {SecureSharingWeb.Endpoint, :cors_origins, []},
    allow_headers: ["authorization", "content-type", "x-requested-with"],
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_credentials: true,
    max_age: 86_400

  plug Plug.Session, @session_options
  plug SecureSharingWeb.Router

  @doc false
  def cors_origins do
    Application.get_env(:secure_sharing, :cors_origins, [
      "https://app.securesharing.app",
      "tauri://localhost",
      "http://localhost:5173"
    ])
  end
end
